MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/fatih/.cache/torch/checkpoints/deit_small_patch16_224.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'deit_small_patch16_224_TransReID'
  STRIDE_SIZE: [12, 12]
  SIE_CAMERA: False
  SIE_COE: 3.0
  JPM: True
  RE_ARRANGE: False

INPUT:
  SIZE_TRAIN: [256, 256]   #[256, 256]
  SIZE_TEST: [256, 256]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('uavswarm')
  ROOT_DIR: ('')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 200
  BASE_LR: 0.008
  IMS_PER_BATCH: 16
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 50
  LOG_PERIOD: 50
  EVAL_PERIOD: 10
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  MARGIN: 0.3

TEST:
  EVAL: True
  IMS_PER_BATCH: 16
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'bn'
  FEAT_NORM: 'yes'

OUTPUT_DIR: ''